import 'dart:math';

final List<Map<String, String>> flashcards = [
  {'word': 'Ciao', 'translation': 'Hello'},
  {'word': 'Addio', 'translation': 'Bye'},
  {'word': 'Italia', 'translation': 'Italy'},
  {'word': 'E', 'translation': 'And'},
  {'word': 'O', 'translation': 'Or'},
  {'word': 'Latte', 'translation': 'Milk'},
  {'word': 'Caffè', 'translation': 'Coffee'},
  {'word': 'Tè', 'translation': 'Tea'},
  {'word': 'Per favore', 'translation': 'Please'},
  {'word': 'Vino', 'translation': 'Wine'},
  {'word': 'Birra', 'translation': 'Beer'},
  {'word': 'Pane', 'translation': 'Bread'},
  {'word': 'Acqua', 'translation': 'Water'},
  {'word': 'Grazie', 'translation': 'Thank you/Thanks'},
  {'word': 'Sì', 'translation': 'Yes'},
  {'word': 'No', 'translation': 'No'},
  {'word': 'Io', 'translation': 'I'},
  {'word': 'Sono', 'translation': 'Am'},
  {'word': 'Tu', 'translation': 'You'},
  {'word': 'Un/Una', 'translation': 'A'},
  {'word': 'Mio/Mia', 'translation': 'My'},
  {'word': 'Madre', 'translation': 'Mother'},
  {'word': 'Padre', 'translation': 'Father'},
  {'word': 'Sorella', 'translation': 'Sister'},
  {'word': 'Fratello', 'translation': 'Brother'},
  {'word': 'Uomo', 'translation': 'Man/Husband'},
  {'word': 'Donna', 'translation': 'Woman/Wife'},
  {'word': 'Figlio', 'translation': 'Son'},
  {'word': 'Figlia', 'translation': 'Daughter'},
  {'word': 'Molto', 'translation': 'Very'},
  {'word': 'Grande', 'translation': 'Tall/Big'},
  {'word': 'Piccolo', 'translation': 'Small'},
  {'word': 'Intelligente', 'translation': 'Smart'},
  {'word': 'Gentile', 'translation': 'Nice'},
  {'word': 'Il/La/Lo', 'translation': 'The'},
  {'word': 'Ragazzo', 'translation': 'Boy'},
  {'word': 'Giovane', 'translation': 'Young'},
  {'word': 'Bello', 'translation': 'Beautiful'},
  {'word': 'Elefante', 'translation': 'Elephant'},
  {'word': 'Cane', 'translation': 'Dog'},
  {'word': 'Gatto', 'translation': 'Cat'},
  {'word': 'Topo', 'translation': 'Mouse'},
  {'word': 'Orso', 'translation': 'Bear'},
  {'word': 'Gufo', 'translation': 'Owl'},
  {'word': 'Renna', 'translation': 'Reindeer'},
  {'word': 'Dove', 'translation': 'Where'},
  {'word': 'Che', 'translation': 'What'},
  {'word': 'Come', 'translation': 'How'},
  {'word': 'Da', 'translation': 'From'},
  {'word': 'Felice', 'translation': 'Happy'},
  {'word': 'Ottimo', 'translation': 'Great'},
  {'word': 'Buono', 'translation': 'Good'},
  {'word': 'Come stai', 'translation': 'How are you?'},
  {'word': 'Va bene', 'translation': 'I am all right'},
  {'word': 'Arrivederci', 'translation': 'Goodbye'},
  {'word': 'Salute', 'translation': 'Cheers'},
  {'word': 'A presto', 'translation': 'See you soon'},
  {'word': 'A dopo', 'translation': 'See you later'},
  {'word': 'Certo', 'translation': 'Of course'},
  {'word': 'Formaggio', 'translation': 'Cheese'},
  {'word': 'Insalata', 'translation': 'Salad'},
  {'word': 'Con', 'translation': 'With'},
  {'word': 'Delizioso', 'translation': 'Delicious'},
  {'word': 'Caldo', 'translation': 'Hot'},
  {'word': 'Freddo', 'translation': 'Cold'},
  {'word': 'Qui', 'translation': 'Here'},
  {'word': 'Uovo', 'translation': 'Egg'},
  {'word': 'Acqua minerale', 'translation': 'Mineral water'},
  {'word': 'Menu', 'translation': 'Menu'},
  {'word': 'Cameriere', 'translation': 'Waiter'},
  {'word': 'Scusa', 'translation': 'Excuse me'},
  {'word': 'Sale', 'translation': 'Salt'},
  {'word': 'Salsiccia', 'translation': 'Sausage'},
  {'word': 'Cibo', 'translation': 'Food'},
  {'word': 'Conto', 'translation': 'Check'},
  {'word': 'Troppo', 'translation': 'Too'},
  {'word': 'Meraviglioso', 'translation': 'Wonderful'}
];



void shuffleFlashcards() {
  flashcards.shuffle(Random());
}